name: Build and Deploy iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
      - name: Install dependencies
        run: pod install
      - name: Build the app
        run: sh ./scripts/prepare-and-build-fast.sh
      
      - name: Deploy IPA
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: ./
