name: Build and Deploy iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        uses: xcodebuild/setup-xcode@v3
        with:
          xcode-version: '14.3'
      - name: Install dependencies
        run: pod install
      - name: Build the app
        run: sh ./scripts/prepare-and-build-fast.sh
      
      - name: Deploy IPA
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: ./
